name: school_ai_assistant
description: AI-Powered Educational Assistant for Schools
# This is a version number for your application
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase packages
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.9.1
  firebase_storage: ^11.2.6
  
  # State management
  provider: ^6.0.5
  
  # UI components and utilities
  cupertino_icons: ^1.0.6
  file_picker: ^10.1.9
  path_provider: ^2.1.0
  open_file: ^3.3.2
  share_plus: ^7.1.0
  pdf: ^3.10.4
  
  # HTTP client for API calls
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  
  # App assets
  assets:
    - assets/images/
  
  # App fonts
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
