// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD69CP1Tuwvbz_ZTQM09z58Woya4BJuzHg',
    appId: '1:4992904430:web:d976b78645558316afd7ff',
    messagingSenderId: '4992904430',
    projectId: 'school-ai-assistant',
    authDomain: 'school-ai-assistant.firebaseapp.com',
    storageBucket: 'school-ai-assistant.firebasestorage.app',
    measurementId: 'G-X8N3B4SZFH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_Wo56RBIZ3ISzen75rvLcBwnXLtCA4Gg',
    appId: '1:4992904430:android:5ecb33d62982403fafd7ff',
    messagingSenderId: '4992904430',
    projectId: 'school-ai-assistant',
    storageBucket: 'school-ai-assistant.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFLWkCejPCb1Jb8tumSGWe_MRD6MfQ8oY',
    appId: '1:4992904430:ios:e7d3b40c87e60f0eafd7ff',
    messagingSenderId: '4992904430',
    projectId: 'school-ai-assistant',
    storageBucket: 'school-ai-assistant.firebasestorage.app',
    iosBundleId: 'com.example.eduassist',
  );
}
